services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_spark_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./house_prices.csv:/house_prices.csv
 
  spark-master:
    image:  bitnami/spark:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      -POSTGRES_HOST: postgres
      -POSTGRES_PORT: 5432
      -POSTGRES_DB: db_spark_app
      -POSTGRES_USER: user
      -POSTGRES_PASSWORD: pass123
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - postgres
 
  spark-worker1:
    image:  bitnami/spark:latest
    environment:
      -SPARK_MASTER_HOST: spark-master
    depends_on:
      - spark-master
 
  spark-worker2:
    image:  bitnami/spark:latest
    environment:
      -SPARK_MASTER_HOST: spark-master
    depends_on:
      - spark-master
